# Generated by Django 3.1.4 on 2020-12-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201207_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.FloatField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MA', 'Male'), ('FE', 'Female'), ('NS', 'Prefer Not to Say'), ('NB', 'Non Binary')], max_length=2, null=True, verbose_name='Gender'),
        ),
    ]
