# Generated by Django 3.1.4 on 2021-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201208_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255, verbose_name='Auth Provider'),
        ),
    ]
