# Generated by Django 3.1.4 on 2021-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210112_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('EM', 'email'), ('GO', 'google')], default='email', max_length=2, verbose_name='Auth Provider'),
        ),
    ]
